name: PYTEST CI 

on: 
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  run-shell-build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]

    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: python commands
        run: |
          import platform 
          print(platform.processor())
        shell: python

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"

      - name: Install pytest
        run: |
          pip install pytest

      - name: Run tests
        run: |
          pytest
          



