name: PYTEST CI 
on: 
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
jobs:
  run-shell-build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - os: macos-latest
          - os: windows-latest
            
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: python commands
        run: |
          import platform 
          print(platform.processor())
        shell: python

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies & pytest unittest 
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run Test with pytest
        run: |
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      



